import { GoogleGenAI } from "@google/genai";
import { storeToAzure } from "./uploadingToAzure";

const ai = new GoogleGenAI({
    apiKey: process.env.GEMINI_API_KEY!,
});

type GeminiPart =
    | { text?: string }
    | {
          inlineData: {
              mimeType: string;
              data: string; // base64
          };
      };

export const generateImageFromTextGemini = async (
    enhancedPrompt: string,
): Promise<string> => {
    const response = await ai.models.generateContent({
        model: "gemini-2.5-flash-image",
        contents: [
            {
                role: "user",
                parts: [{ text: enhancedPrompt }],
            },
        ],
    });

    const parts = response.candidates?.[0]?.content?.parts as GeminiPart[];

    if (!parts) {
        throw new Error("No content returned from Gemini");
    }

    for (const part of parts) {
        if ("text" in part) continue;
        if ("inlineData" in part) {
            const { data, mimeType } = part.inlineData;
            const buffer = Buffer.from(data, "base64");
            const imageUrl = await storeToAzure(
                buffer,
                mimeType || "image/png",
            );
            return imageUrl;
        }
    }
    throw new Error("No image generated by Gemini");
};

export const generateImageFromImgTxtGemini = async (
    base64Image: string,
    userPrompt: string,
) => {
    const prompt = [
        {
            text: `You are a professional commercial product photographer and visual designer.

                Analyze the provided product image carefully and preserve the product's exact shape, color, texture, and proportions.

                Your task is to generate a high-quality, photorealistic product image suitable for an e-commerce website.

                Follow these rules strictly:
                - Keep the product identity unchanged
                - Do NOT distort or modify the product
                - Do NOT add text, logos, or watermarks
                - Do NOT add people or hands
                - The product must be the clear focal point
                - Use realistic lighting, shadows, and reflections
                - Produce a clean, professional, studio-quality result

                User’s scene request:
                "${userPrompt}"

                Visual style requirements:
                - High resolution
                - Sharp focus
                - Natural depth of field
                - Commercial studio lighting
                - Neutral color grading
                - Professional advertising photography

                Return only the final generated image. No explanations.
            `,
        },
        {
            inlineData: {
                mimeType: "image/png",
                data: base64Image,
            },
        },
    ];

    const response = await ai.models.generateContent({
        model: "gemini-2.5-flash-image",
        contents: prompt,
    });

    const parts = response.candidates?.[0]?.content?.parts as GeminiPart[];

    if (!parts) {
        throw new Error("No content returned from Gemini");
    }

    for (const part of parts) {
        if ("text" in part) continue;
        if ("inlineData" in part) {
            const { data, mimeType } = part.inlineData;
            const buffer = Buffer.from(data, "base64");
            const imageUrl = await storeToAzure(
                buffer,
                mimeType || "image/png",
            );
            return imageUrl;
        }
    }
    throw new Error("No image generated by Gemini");
};
