import { InferenceClient } from "@huggingface/inference";
import dotenv from "dotenv";
import { storeToAzure } from "./uploadingToAzure";

dotenv.config();

const client = new InferenceClient(process.env.HF_TOKEN);

export const generateImageHuggingFace = async (enhancedPrompt: any, userPrompt: string) => {
    try {
        const image: any = await client.textToImage({
            provider: "together",
            model: "black-forest-labs/FLUX.1-dev",
            inputs: `${userPrompt} and ${enhancedPrompt}`,
            parameters: { num_inference_steps: 5 },
        });

        const arrayBuffer = await image.arrayBuffer();
        const buffer = Buffer.from(arrayBuffer);
        const imageUrl = await storeToAzure(buffer, image?.type);

        return imageUrl;
    } catch (error) {
        console.log(error)
        throw new Error("No image generated by Hugging Face");
    }
};
